import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Button, Typography } from '@mui/material';

import { useAppDispatch, useAppSelector } from '../store/hooks';
import { isLoggedInSelector, login, logout } from '../store/reducers/auth/authSlice';
import Layout from '../layouts/Layout';

const Home: NextPage = () => {
  const isAuth = useAppSelector(isLoggedInSelector);
  const dispatch = useAppDispatch();
  return (
    <div>
      <Head>
        <title>WorkShare</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Layout>
        <main>
          <p className='text-3xl font-bold underline'>Text</p>
          <Typography
            pt={4}
            className='text-3xl font-bold underline'>
            {isAuth ? 'You was logged in' : 'You was logged out'}
          </Typography>
          <Button
            variant='outlined'
            onClick={() => (isAuth ? dispatch(logout()) : dispatch(login()))}>
            {isAuth ? 'Logout' : 'LogIn'}
          </Button>
        </main>
      </Layout>
    </div>
  );
};

export default Home;
