import type { NextPage } from 'next';
import Head from 'next/head';
import { Button, Typography } from '@mui/material';
import theme from '../src/styles/theme';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>WorkShare</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Typography style={{ margin: theme.spacing(6) }}>
          {' '}
          Hello WorkShare
        </Typography>
        <Button style={{ margin: theme.spacing(6) }} variant='outlined'>
          Click Me
        </Button>
      </main>
    </div>
  );
};

export default Home;
