import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Button, Typography } from '@mui/material';
import theme from '../src/styles/theme';

import { useAppDispatch, useAppSelector } from '../store/hooks';
import { isLoggedInSelector, login, logout } from '../store/reducers/auth/authSlice';

const Home: NextPage = () => {
  const isAuth = useAppSelector(isLoggedInSelector);
  const dispatch = useAppDispatch();
  return (
    <div>
      <Head>
        <title>WorkShare</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <main>
        <Typography style={{ margin: theme.spacing(6) }}>
          {isAuth ? 'You was logged in' : 'You was logged out'}
        </Typography>
        <Button
          style={{ margin: theme.spacing(6) }}
          variant='outlined'
          onClick={() => (isAuth ? dispatch(logout()) : dispatch(login()))}>
          {isAuth ? 'Logout' : 'LogIn'}
        </Button>
      </main>
    </div>
  );
};

export default Home;
